name: "Kitty's Kombucha"
favicon: null
layout_spectrum: 0.6324734869413078
typography_spectrum: 0.02470588660798967
title: "Kitty's Kombucha"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5921631206292659
  lightness: 0.6029529073275626
  saturation: 0.8896394106559455
  rhythmicContrast: 0.4351932895369828
purpose: []
